/**
 * APEX AUTO PARTS - GLOBAL PRODUCT CATALOG
 * This dataset represents the high-performance benchmark for precision engineering components.
 * Use this to seed the production database or build the search index.
 */

export const APEX_CATALOG = [
  {
    id: "apx-brk-001",
    name: "Ceramic Performance Brake Pads",
    category: "Braking Systems",
    brand: "Apex Racing",
    sku: "AR-BRK-CER-001",
    price: 129.99,
    stock: 45,
    description: "Multi-layered ceramic compound with noise-reduction shims. Engineered for zero fade under extreme thermal stress.",
    specs: { material: "Carbon-Ceramic", warranty: "2 Years", fits: ["Sport Sedan", "GT Coupe"] },
    image: "https://images.unsplash.com/photo-1598083842605-7af83fb18ebd?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "apx-eng-002",
    name: "Synthetic V-Twin Engine Oil 10W-60",
    category: "Fluids & Lubricants",
    brand: "Titan-Oil",
    sku: "TO-SYN-1060-VT",
    price: 18.50,
    stock: 250,
    description: "Fully synthetic ester-based lubricant specifically formulated for air-cooled high-displacement engines.",
    specs: { vis: "10W-60", volume: "1 Liter", api: "SN/CF" },
    image: "https://images.unsplash.com/photo-1610493864198-4eabd27df61a?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "apx-int-003",
    name: "High-Flow Cold Air Intake System",
    category: "Air Induction",
    brand: "Aero-Dynamic",
    sku: "AD-INT-CF-99",
    price: 349.00,
    stock: 12,
    description: "Lightweight carbon fiber intake housing with high-flow reusable cotton filter. Increases oxygen saturation for combustion.",
    specs: { flow: "800 CFM", material: "Carbon Fiber", gain: "+12 HP" },
    image: "https://images.unsplash.com/photo-1610493863481-9b7e779a543f?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "apx-sus-004",
    name: "Adjustable Coilover Suspension Kit",
    category: "Suspension",
    brand: "Track-Spec",
    sku: "TS-SUS-ADJ-X4",
    price: 1299.00,
    stock: 8,
    description: "32-way damping adjustable coilovers. Inverted mono-tube design for immediate response and body roll mitigation.",
    specs: { type: "Mono-Tube", height: "Adjustable -2.5\"", damper: "32-Way" },
    image: "https://images.unsplash.com/photo-1621932970671-8798ef73286f?auto=format&fit=crop&q=80&w=800"
  },
  // --- EXTENDED CATALOG DATA ---
  { id: "apx-ele-005", name: "Lithium-Ion Lightweight Battery", category: "Electrical", brand: "Volt-Edge", price: 499.00, stock: 22 },
  { id: "apx-ext-006", name: "Front Splitter - Carbon Composites", category: "Aero", brand: "Apex Racing", price: 550.00, stock: 5 },
  { id: "apx-ext-007", name: "Rear Wing Spoiler - GT Style", category: "Aero", brand: "Apex Racing", price: 890.00, stock: 3 },
  { id: "apx-eng-008", name: "Forged Aluminum Pistons - Set of 4", category: "Engine", brand: "Titan-Engine", price: 720.00, stock: 15 },
  { id: "apx-eng-009", name: "High-Lift Camshaft - Stage 2", category: "Engine", brand: "Titan-Engine", price: 420.00, stock: 10 },
  { id: "apx-brk-010", name: "Stainless Steel Braided Brake Lines", category: "Braking", brand: "Apex Racing", price: 145.00, stock: 60 },
  { id: "apx-ign-011", name: "Iridium Performance Spark Plugs - 4pk", category: "Ignition", brand: "Volt-Edge", price: 44.99, stock: 120 },
  { id: "apx-trs-012", name: "Short Throw Shifter Assembly", category: "Transmission", brand: "Shift-Master", price: 189.00, stock: 25 },
  { id: "apx-trs-013", name: "Lightweight Flywheel - Billets", category: "Transmission", brand: "Shift-Master", price: 340.00, stock: 18 },
  { id: "apx-exh-014", name: "Cat-Back Dual Exhaust System", category: "Exhaust", brand: "Aero-Dynamic", price: 850.00, stock: 7 },
  { id: "apx-exh-015", name: "Stainless Steel Headers - 4-to-1", category: "Exhaust", brand: "Aero-Dynamic", price: 480.00, stock: 12 },
  { id: "apx-whl-016", name: "Forged Monoblock Wheels - 19 inch", category: "Wheels", brand: "Apex Racing", price: 2400.00, stock: 4 },
  { id: "apx-whl-017", name: "Performance Lug Nuts - Titanium", category: "Wheels", brand: "Apex Racing", price: 150.00, stock: 40 },
  { id: "apx-int-018", name: "Racing Bucket Seat - FIA Approved", category: "Interior", brand: "Apex Racing", price: 950.00, stock: 6 },
  { id: "apx-int-019", name: "Alcantara Steering Wheel Wrap Kit", category: "Interior", brand: "Apex Racing", price: 85.00, stock: 35 },
  { id: "apx-ele-020", name: "Dashcam 4K - Intelligent Monitoring", category: "Electrical", brand: "Volt-Edge", price: 199.00, stock: 50 },
  { id: "apx-cln-021", name: "Ceramic Coating Detailer - 500ml", category: "Care", brand: "Gloss-Works", price: 35.00, stock: 100 },
  { id: "apx-cln-022", name: "Microfiber Premium Wash Mitt", category: "Care", brand: "Gloss-Works", price: 12.00, stock: 200 },
  { id: "apx-cln-023", name: "pH Neutral Wheel Cleaner", category: "Care", brand: "Gloss-Works", price: 22.00, stock: 85 },
  { id: "apx-tires-024", name: "Semi-Slick Track Tires - 245/40R18", category: "Tires", brand: "Track-Master", price: 280.00, stock: 16 },
  { id: "apx-tires-025", name: "All-Season Ultra High Performance", category: "Tires", brand: "Track-Master", price: 210.00, stock: 24 },
  { id: "apx-brk-026", name: "Big Brake Kit - 6-Piston Calipers", category: "Braking", brand: "Apex Racing", price: 2800.00, stock: 2 },
  { id: "apx-eng-027", name: "Oil Catch Can - Dual Reservoir", category: "Engine", brand: "Titan-Engine", price: 160.00, stock: 30 },
  { id: "apx-int-028", name: "Digital Gauge Pod - OBD-II", category: "Interior", brand: "Volt-Edge", price: 249.00, stock: 14 },
  { id: "apx-ele-029", name: "LED Headlight Conversion Kit", category: "Electrical", brand: "Volt-Edge", price: 120.00, stock: 55 },
  { id: "apx-sus-030", name: "Anti-Roll Sway Bar Upgrade Kit", category: "Suspension", brand: "Track-Spec", price: 380.00, stock: 20 },
  { id: "apx-sus-031", name: "Adjustable Camber Plates", category: "Suspension", brand: "Track-Spec", price: 220.00, stock: 18 },
  { id: "apx-trs-032", name: "Performance Clutch Kit - Stage 3", category: "Transmission", brand: "Shift-Master", price: 540.00, stock: 9 },
  { id: "apx-aero-033", name: "Carbon Fiber Fog Light Bezels", category: "Aero", brand: "Apex Racing", price: 110.00, stock: 40 },
  { id: "apx-exh-034", name: "High-Flow Sports Catalytic Converter", category: "Exhaust", brand: "Aero-Dynamic", price: 450.00, stock: 15 },
  { id: "apx-eng-035", name: "Billet Aluminum Pulley Set", category: "Engine", brand: "Titan-Engine", price: 290.00, stock: 12 },
  { id: "apx-brk-036", name: "Rear Brake Rotor - Slotted/Drilled", category: "Braking", brand: "Apex Racing", price: 95.00, stock: 50 },
  { id: "apx-brk-037", name: "Front Brake Rotor - 355mm Semi-Float", category: "Braking", brand: "Apex Racing", price: 220.00, stock: 28 },
  { id: "apx-ign-038", name: "High-Output Ignition Coils", category: "Ignition", brand: "Volt-Edge", price: 280.00, stock: 22 },
  { id: "apx-int-039", name: "4-Point Harness - Cam-Lock", category: "Interior", brand: "Apex Racing", price: 165.00, stock: 12 },
  { id: "apx-ext-040", name: "Rear Diffuser - Carbon Composites", category: "Aero", brand: "Apex Racing", price: 620.00, stock: 6 },
  { id: "apx-eng-041", name: "Performance Fuel Injectors - 750cc", category: "Engine", brand: "Titan-Engine", price: 340.00, stock: 25 },
  { id: "apx-eng-042", name: "High-Lift Fuel Pump - 340 LPH", category: "Engine", brand: "Titan-Engine", price: 180.00, stock: 35 },
  { id: "apx-sus-043", name: "Polyurethane Bushing Kit - Full Set", category: "Suspension", brand: "Track-Spec", price: 210.00, stock: 20 },
  { id: "apx-whl-044", name: "Wheel Spacer Kit - 15mm with Bolts", category: "Wheels", brand: "Apex Racing", price: 125.00, stock: 48 },
  { id: "apx-cln-045", name: "Iron & Fallout Remover - 1 Liter", category: "Care", brand: "Gloss-Works", price: 28.00, stock: 60 },
  { id: "apx-ele-046", name: "Portable Jump Starter - 2000A Peak", category: "Electrical", brand: "Volt-Edge", price: 149.00, stock: 75 },
  { id: "apx-int-047", name: "Custom Floor Mats - Carbon Look", category: "Interior", brand: "Apex Racing", price: 120.00, stock: 30 },
  { id: "apx-eng-048", name: "Magnetic Oil Drain Plug", category: "Engine", brand: "Titan-Engine", price: 18.00, stock: 500 },
  { id: "apx-brk-049", name: "Brake Fluid - DOT 5.1 Racing", category: "Braking", brand: "Apex Racing", price: 24.00, stock: 144 },
  { id: "apx-tires-050", name: "Compact Spare Tire Kit", category: "Tires", brand: "Track-Master", price: 175.00, stock: 10 }
];
